import { Roboto_Serif } from "next/font/google";
import "./globals.css";
import Navigation from "@/components/Shared/Navigation/Navigation";

const inter = Roboto_Serif({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navigation />
        {children}
      </body>
    </html>
  );
}
